# Generated by Django 3.2 on 2021-04-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40, verbose_name='نام')),
                ('lastname', models.CharField(max_length=40, verbose_name='نام خانوادگی')),
                ('username', models.CharField(max_length=30, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل ')),
                ('datebirth', models.DateField(verbose_name='تاریخ تولد')),
                ('city', models.CharField(max_length=20, verbose_name='شهر')),
                ('idcard', models.BigIntegerField(verbose_name='کد ملی')),
                ('fathername', models.CharField(max_length=40, verbose_name='نام پدر')),
                ('gender', models.CharField(choices=[('men', 'مرد'), ('women', 'زن'), ('other', 'دیگر')], max_length=10, verbose_name='جنسیت')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postcode', models.CharField(blank=True, max_length=12, null=True, verbose_name='کد پستی')),
                ('phone_mobile', models.CharField(max_length=40, verbose_name='شماره مبایل ')),
                ('phone_home', models.CharField(max_length=40, verbose_name='شماره منزل')),
                ('religen', models.CharField(blank=True, max_length=40, null=True, verbose_name='دین')),
                ('maritalstatus', models.BooleanField(default=False, verbose_name='وضعیت تاهل')),
                ('job', models.CharField(blank=True, max_length=40, null=True, verbose_name='شغل')),
                ('education', models.CharField(max_length=40, verbose_name='تحصیلات')),
                ('Universitydegree', models.CharField(blank=True, max_length=40, null=True, verbose_name='مدرک دانشگاهی')),
                ('university', models.CharField(blank=True, max_length=40, null=True, verbose_name='دانشگاه')),
                ('password', models.TextField(verbose_name='پسورد')),
            ],
            options={
                'verbose_name': 'اهراز هویت کاربر',
                'verbose_name_plural': 'اهراز هویت کاربران',
            },
        ),
    ]
